@ECHO OFF
:ANDRSON131A
TITLE ANDERSON131ASERVER/STARTING!|COLOR A|ECHO STARTINGSERVER...
SET BINDIR=%~dp0
CD /D "%BINDIR%"
java -Xmx1024M -jar spigot-1.11.jar
TITLE ANDERSON131ASERVER/RESTART!|ECHO ANDERSON131ASERVER/RESTART !
TIMEOUT 33
GOTO ANDRSON131A
START ANDERSON131ASERVERSTART.bat|TITLE ANDERSON131ASERVER
EXIT|PAUSE|TIMEOUT 0
EXIT